name: Auto Release

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: read

jobs:
  auto_release:
    env:
      OWNER: "Privado-Inc"
      BRANCH: "main"
      REPO: "njs_accounts"
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Create an incremental tag
        id: generate-tag
        run: |
          latest_tag=$(gh api repos/$OWNER/$REPO/tags --jq '.[0].name')
          
          new_tag=$(echo $latest_tag | awk -F. '{print $1"."$2"."$3+1}')
          
          latest_commit_sha=$(gh api repos/$OWNER/$REPO/git/refs/heads/$BRANCH --jq '.object.sha')
          
          gh api repos/$OWNER/$REPO/git/refs \
          -f ref="refs/tags/$new_tag" \
          -f sha=$latest_commit_sha
          
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT                

      - name: Create and publish release
        run: gh release create ${{ steps.generate-tag.outputs.new_tag }} --generate-notes --target main --title "${{ steps.generate-tag.outputs.new_tag }} 🚀" --repo "${{ env.OWNER }}/${{ env.REPO }}"